# starship settings of:
# -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
# -=-=-=-=-=-=-=-=-=- Mart 󱃱 -=-=-=-=-=-=-=-=-=-=-=-
# -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
# Nerd font required, check out: https://www.nerdfonts.com/#home 

format = """
[ 󰣇 ](fg:#1E1E24 bold bg:#FF5400)\
[](fg:#FF5400 bg:#FF7900)\
$localip\
[](fg:#FF7900 bg:#FF8500)\
$time\
[](fg:#FF8500 bg:#f48c06)\
$directory\
[](fg:#f48c06 bg:#faa307)\
$git_branch\
$git_status\
[](fg:#faa307 bg:#ffba08)\
$cmd_duration\
[](fg:#ffba08)\
\n$battery$character"""

[localip]
ssh_only = false
style = "fg:#1E1E24 bold bg:#FF7900"
format = '[  $localipv4 ]($style)'
disabled = false

[time]
disabled = false
time_format ="%R"
style = "fg:#1E1E24 bold bg:#FF8500"
format = '[[  $time ]($style)]($style)'

[directory]
style = "fg:#1E1E24 bold bg:#f48c06"
format = "[  $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[git_branch]
symbol = ""
style = "fg:#1E1E24 bold bg:#faa307"
format = '[[ $symbol $branch ]($style)]($style)'

[git_status]
style = "fg:#1E1E24 bold bg:#faa307"
format = '[[($all_status$ahead_behind )]($style)]($style)'

[cmd_duration]
min_time = 100
style = "fg:#1E1E24 bold bg:#ffba08"
format = "[  $duration ]($style)"

[battery]
charging_symbol = '[ 󰂅 ](#8dc29e)'

[[battery.display]]
threshold = 10
style = 'bold #D42136'
discharging_symbol  = '  '

[[battery.display]]
threshold = 50
style = 'bold #F66451'
discharging_symbol  = ' 󰞲 '

[[battery.display]]
threshold = 70
style = 'bold #F69C3C'
discharging_symbol  = ' 󰑮 '

[[battery.display]]
threshold = 100
style = '#8dc29e' # light green
discharging_symbol  = ' 󱙣 '

